### ISSUE TITLE
Quitad comentarios suplerfluos

### ISSUE THREAD

**Issue by lmagarin** [damian-miquel/Almacen#2]
https://github.com/damian-miquel/Almacen/blob/b685ec78bd32d281f55b091aaa911fd5b25e14f9/negocio/Articulo.java#L25

Este artículo es demasiado práctico, pero tiene algo de razón
https://blog.jmbeas.es/2009/02/03/los-comentarios-en-el-codigo-son-basura/

**Comment by damian-miquel** [comment]
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/gestion/Articulo.java#L1-L151
