### ISSUE TITLE
Usa StringBuilder en vez de String. Es más eficiente. String es inmutable.

### ISSUE THREAD

**Issue by lmagarin** [damian-miquel/Almacen#3]
https://github.com/damian-miquel/Almacen/blob/b685ec78bd32d281f55b091aaa911fd5b25e14f9/negocio/Articulo.java#L109
Cada vez que modificas String creas una nueva y deshechas la anterior. Usa StringBuilder

**Comment by damian-miquel** [comment]
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/gestion/Articulo.java#L145-L150
