### ISSUE TITLE
Volvéis a hacer la misma asignación que arriba. Asignáis dos veces

### ISSUE THREAD

**Issue by lmagarin** [damian-miquel/Almacen#5]
https://github.com/damian-miquel/Almacen/blob/b685ec78bd32d281f55b091aaa911fd5b25e14f9/negocio/Articulo.java#L18

**Comment by damian-miquel** [comment]
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/gestion/Articulo.java#L28
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/gestion/Articulo.java#L31-L38
