### ISSUE TITLE
Extraed método setStock que lance la excepción 

### ISSUE THREAD

**Issue by lmagarin** [damian-miquel/Almacen#6]
https://github.com/damian-miquel/Almacen/blob/b685ec78bd32d281f55b091aaa911fd5b25e14f9/negocio/Articulo.java#L22

if (unidades < 0)
			throw new StockNegativoException("El stock del artículo no puede ser negativo");

**Comment by damian-miquel** [comment]
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/gestion/Articulo.java#L139-L143
