### ISSUE TITLE
Aquí capturad la excepción lanzada en setStock

### ISSUE THREAD

**Issue by lmagarin** [damian-miquel/Almacen#7]
https://github.com/damian-miquel/Almacen/blob/b685ec78bd32d281f55b091aaa911fd5b25e14f9/presentacion/TestAlmacen.java#L172

```
private static void alta() {
		try {
			almacen.add(Teclado.getCadena("Introduce la descripción"), Teclado.getDecimal("Precio de compra: "),
					Teclado.getDecimal("Precio de venta: "), Teclado.getEntero("Número de unidades: "));
		} catch (StockNegativoException e) {
			System.err.println("No se ha podido dar de alta al artículo. "+e.getMessage());
		}
	}
```

**Comment by damian-miquel** [comment]
En la clase Almacen lanzamos la exceción:
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/gestion/Almacen.java#L15-L30

Y aquí capturamos la excepción:
https://github.com/damian-miquel/Almacen/blob/079ece1957b4de149e385b992f05c5c5f87809c6/presentacion/TestAlmacen.java#L119-L147
